### ISSUE TITLE
Upload new glossary terms to Crowdin

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#231]
In https://github.com/nodejs/i18n/pull/91 we introduced a new glossary file! The next step will be to upload these terms to the Crowdin project using Crowdin's API and the https://github.com/crowdin-node/crowdin-glossary npm module.

Details for this process are covered in the OP of this issue: https://github.com/nodejs/i18n/issues/81

cc @alexandrtovmach @maddhruv

**Comment by maddhruv** [comment]
The ideal way I see to automate the upload is to listen for changes in the corresponding sources - builtins, crowdin-glossary.json, we would run the upload then - maybe via GitHub Actions and automated.

One problem solution - Use github actions and look for path changes and run the upload script, Ref - https://github.com/nodejs/i18n/pull/237#issuecomment-599165872

@zeke if we agree onto this, let's add the `CROWDIN_KEY` to the GitHub secrets

**Comment by nschonni** [comment]
Here is a sample action file `glossary.yml`
```yml
name: Upload Crowdin Glossary

on:
  push:
    branches:
    - master
    paths:
    - "crowdin-glossary.json"
    - "script/upload-crowdin-glossary.js"
    - "package.json"
    - "package-lock.json"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: npm ci

      - name: Upload Glossary
        run: npm run upload-crowdin-glossary
```
Don't know enough to see where the Key is needed. You can expose a secret as an environment variable like https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow
