### ISSUE TITLE
File structure and crowdin.yml

### ISSUE THREAD

**Issue by zeke** [nodejs/i18n#61]
When @vanessayuenn and I implemented #55, we chose this directory structure for content:

```
/content/{nodeVersion}/{languageCode}/doc
```

for example:

```
/content/v8.11.1/en-US/doc
/content/v9.10.1/en-US/doc
```

Now that I think about how we'll write the [crowdin.yml](https://support.crowdin.com/configuration-file/) file, I'm wondering how we can account for multiple Node.js version directories without having to rewrite the YML file every time we change the list of target versions.

In other words, wondering how we can avoid this:

```yml
files:
  - source: /content/v8.11.1/en-US/doc/**/.md
    translation: /content/v8.11.1/%locale%/doc/**/%original_file_name%
  - source: /content/v9.10.1/en-US/doc/**/*.md
    translation: /content/v9.10.1/%locale%/doc/**/%original_file_name%
```

And do something more like this:

```yml
files:
  - source: /content/**/en-US/doc/**/*.md
    translation: /content/**/%locale%/doc/**/%original_file_name%
```

@andrulko will this work?
